FROM php:5-fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
		&& docker-php-ext-configure mysql --with-pdo-mysql=mysqlnd \
		&& docker-php-ext-install mysql \
		&& docker-php-ext-configure mysqli --with-pdo-mysql=mysqlnd \
		&& docker-php-ext-install mysqli \
		&& docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
		&& docker-php-ext-install pdo_mysql \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
